<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xs:element name="sailkapena">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="taldea" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="izena" type="xs:string"/>
                            <xs:element name="logoa" type="xs:string"/>
                            <xs:element name="puntuak" type="xs:integer"/>
                            <xs:element name="jp" type="xs:integer"/>
                            <xs:element name="irabaziak" type="xs:integer"/>
                            <xs:element name="galerak" type="xs:integer"/>
                            <xs:element name="ap" type="xs:integer"/>
                            <xs:element name="kp" type="xs:integer"/>
                        </xs:sequence>
                        <xs:attribute name="pos" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>